### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by edobrb** [bmp-git/PPS-18-scala-mqtt#1]
- [x] Project structure #3
- [x] Configure IDE #2 
- [x] Configure gradle build #4
- [x] Configure style plugins #5
- [x] Prepare travis CI configuration #6
- [x] Gitignore #7
