### ISSUE TITLE
As a client, I want to connect and disconnect from the MQTTbroker

### ISSUE THREAD

**Issue by Panchhh** [bmp-git/PPS-18-scala-mqtt#10]
- [x] Develop MQTT packets parser, at least connect/disconnect #11

- [x] Develop MQTT packets builder, at least connack #12

- [x] Develop MQTT protocol manager, at least create/cancel sessions #13

- [ ] Simple integration test

- [ ] Integration using reactive streams
