### ISSUE TITLE
As a client I want to publish a message in a topic and subscribe to a topic.

### ISSUE THREAD

**Issue by edobrb** [bmp-git/PPS-18-scala-mqtt#25]
- [x] Develop publish/subscribe packet parser #26
- [x] Develop publish/subscribe packet builder #27
- [x] Develop MQTT publish/subscribe logic in Protocol Manager (Qos 0) #28 
- [x] Implement topic’s matching logic #31
