### ISSUE TITLE
As a client I want to ping and unsubscribe from topics

### ISSUE THREAD

**Issue by edobrb** [bmp-git/PPS-18-scala-mqtt#40]
- [x] Develop ping/unsubscribe packet parser #43
- [x] Develop ping/unsubscribe packet builder #42
- [x] Develop MQTT ping/unsubscribe logic #44
